# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

import './Fastlane_for_demo'
import './Fastlane_demo'
import './Fastlane_for_pr'

default_platform(:ios)

platform :ios do

  error do |lane, exception|

  end

end
